/**
 * @api {PUT} /auth/change-password PUT - Changes the user's password
 * @apiPermission Admin
 * @apiVersion 1.0.0
 * @apiName PutChangePassword
 * @apiSampleRequest off
 * @apiGroup Auth
 * @apiDescription Changes the user's password
 * @apiParamExample  Example request 
    {
      "currentPassword": "NoneOfyourbusiness123312!",
      "newPassword": "definitelyNotAGoodPassword2233"
    }
 * @apiParam (Request body) {String} currentPassword Your current password
 * @apiParam (Request body) {String} newPassword The new password
 * @apiSuccessExample Example Response
    {
        "success": true,
        "user": {
            "suspended": false,
            "email": "test@tes.com",
            "firstName": "HHH",
            "lastName": "AAA",
            "createdAt": "2021-06-04T17:08:42.929Z",
            "updatedAt": "2021-06-04T17:08:42.929Z",
            "id": "60ba5e1a793e584a80ebfb54"
        }
    }
 * @apiSuccess {Boolean} success Indicates that the password was updated.
 * @apiSuccess {Boolean} user[suspended] User suspended status
 * @apiSuccess {String} user[email] User's Email
 * @apiSuccess {String} user[firstName] User's first name
 * @apiSuccess {String} user[lastName] User's last name
 * @apiSuccess {String} user[createdAt] User created at time - auto-generated by Mongo
 * @apiSuccess {String} user[updatedAt] User updated at time - auto-generated by Mongo
 * @apiSuccess {String} user[id] User id
 * @apiError (Error 400) AuthorizationRequired  <code>The authorization header is required.</code>
 * @apiError (Error 401) RefreshTokenExpired <code>Refresh token has expired.</code>
 * @apiError (Error 401) AccessTokenExpired <code>Access token has expired.</code>
 * @apiError (Error 404) AccountNotFound <code>Account not found.</code>
 * @apiError (Error 400) InputValidation <ul>
 *  <li><code>You must provide your current password.</code></li>
 *  <li><code>Your new password must be between 4 and 20 characters</code></li>
 * </ul>
 * @apiError (Error 400) InvalidCredentials  <code>Invalid credentials.</code>
* @apiErrorExample {json} Example Error Response:
    {
        "errors": [
            {
                "message": "Invalid credentials.",
                "errorType": "InvalidCredentials",
                "statusCode": 400
            }
        ]
    }
* @apiErrorExample {json} InputValidation Response:
    {
        "errors": [
            {
                "message": "You must provide your current password.",
                "field": "currentPassword",
                "errorType": "InputValidation",
                "statusCode": 400
            },
            {
                "message": "Your new password must be between 4 and 20 characters",
                "field": "newPassword",
                "errorType": "InputValidation",
                "statusCode": 400
            }
        ]
}
 */
