/**
 * @api {DELETE} /comments/:id DELETE - Delete Comment
 * @apiPermission Admin only
 * @apiVersion 1.0.0
 * @apiName DeleteComment
 * @apiSampleRequest off
 * @apiGroup Comments
 * @apiDescription  Deletes a comment by id
 * @apiHeaderExample {json} Must include Authorization Header:
 *     {
 *       "Authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTk2N2Q4OGE1ZDJkNTIyYzBkMzExMSIsInJvbGUiOiJwcmltZS1hZG1pbiIsInRrSWQiOiI2MGI0YTA5NTdjMWE2ZjQzOGMxMTRjNjEiLCJyZWZyZXNoVG9rZW4iOiI2MGI0YTA5NTdjMWE2ZjQzOGMxMTRjNjIiLCJpYXQiOjE2MjI0NTAzMjUsImV4cCI6MTYyMjQ1MjEyNX0.HJ3eJsyIIFg3snqU_c0ZCtE6TLSZ8BH-_uk8fGQdvEI"
 *     }
 * @apiParam (Request parameters) {String} id Comment Unique ID.
 * @apiSuccessExample Example Response
    {
        "success": true,
        "comment": {
            "createdAt": "2021-05-23T10:51:48.949Z",
            "content": "I dont care lalalalala",
            "user": "60a967d88a5d2d522c0d3111",
            "articleId": "60aa2a24a79a8c48a05d1436",
            "id": "60aa33c9604e0a2e6c7d4fa7"
        }
    }
 * @apiSuccess {Boolean} success Indicates that the article was deleted.
 * @apiSuccess {String} comment[content] Comment content
 * @apiSuccess {String} comment[user] Comment user id
 * @apiSuccess {String} comment[id] Comment id
 * @apiSuccess {String} comment[createdAt] Comment created at time - auto-generated by Mongo
 * @apiSuccess {String} comment[updatedAt] Comment updated at time - auto-generated by Mongo
 * @apiError (Error 400) InvalidObjectID <code>Please provide a valid object id.</code>
 * @apiError (Error 400) AuthorizationRequired  <code>The authorization header is required.</code>
 * @apiError (Error 401) NotAuthorized  <code>You are not authorized.</code>
 * @apiError (Error 401) RefreshTokenExpired <code>Refresh token has expired.</code>
 * @apiError (Error 401) AccessTokenExpired <code>Access token has expired.</code>
 * @apiError (Error 404) AccountNotFound <code>Account not found.</code>
 * @apiError (Error 404) ResourceNotFound <code>Resource not found.</code>
 * @apiErrorExample {json} Example Error Response:
    {
        "errors": [
            {
                "message": "Resource not found.",
                "errorType": "ResourceNotFound",
                "statusCode": 404
            }
        ]
    }
 */
