/**
 * @api {PUT} /comments/:id PUT - Update a comment
 * @apiPermission Admin
 * @apiVersion 1.0.0
 * @apiName PutComment
 * @apiSampleRequest off
 * @apiGroup Comments
 * @apiDescription Updates a comment
 * @apiParamExample  Example request 
    PUT - /v1/comments/60b5d1d3bfcee136b4551f22
 * @apiParam (Request body) {String} content Content - required 
 * @apiParamExample  Example request 
    {
      "content": "Changed content"
    }
 * @apiSuccessExample Example Response
    {
        "moderated": true,
        "banned": false,
        "content": "Changed content",
        "user": "60b4cccb16d4a119d409057e",
        "articleId": "60ac8cfe8c932132c4fe4173",
        "createdAt": "2021-06-01T06:21:07.951Z",
        "updatedAt": "2021-06-01T07:13:09.322Z",
        "id": "60b5d1d3bfcee136b4551f22"
    }
 * @apiSuccess {Boolean} moderated Is the comment moderated or not.
 * @apiSuccess {Boolean} banned Is the comment banned or not.
 * @apiSuccess {String} content Comment's content
 * @apiSuccess {String} user User who made the comment, MongoDB ID
 * @apiSuccess {String} articleId Article that owns the comment, MongoDB ID
 * @apiSuccess {String} createdAt Article created at time - auto-generated by Mongo
 * @apiSuccess {String} updatedAt Article updated at time - auto-generated by Mongo
 * @apiSuccess {String} id Comment's id
 * @apiError (Error 400) InvalidObjectID <code>Please provide a valid object id.</code>
 * @apiError (Error 400) AuthorizationRequired  <code>The authorization header is required.</code>
 * @apiError (Error 401) NotAuthorized  <code>You are not authorized.</code>
 * @apiError (Error 401) RefreshTokenExpired <code>Refresh token has expired.</code>
 * @apiError (Error 401) AccessTokenExpired <code>Access token has expired.</code>
 * @apiError (Error 404) AccountNotFound <code>Account not found.</code>
 * @apiError (Error 404) ResourceNotFound <code>Resource not found.</code>
 * @apiErrorExample {json} Example Error Response:
    {
        "errors": [
            {
                "message": "Access token has expired.",
                "errorType": "AccessTokenExpired",
                "statusCode": 401
            }
        ]
    }
 */
