/**
 * @api {GET} /articles GET - Get Articles List
 * @apiVersion 1.0.0
 * @apiName GetArticles
 * @apiSampleRequest off
 * @apiGroup Articles
 * @apiDescription  Gets a list of articles
 * @apiParam (Query Parameters) {Number} [page=1] Current page
 * @apiParam (Query Parameters) {Number} [limit=15] Articles per page
 * @apiParam (Query Parameters) {String} [orderBy="createdAt"] Order by field
 * @apiParam (Query Parameters) {String} [orderDir="desc"] Order direction ( asc  | desc )
 * @apiParamExample  Example request 
    GET - /v1/articles?limit=2&page=3&orderBy=title&orderDir=asc
 * @apiSuccessExample Example Response
      {
        "items": [
            {
                "likes": [],
                "comments": [],
                "createdAt": "2021-05-25T05:36:59.212Z",
                "title": "Consequatur aut sapiente praesentium animi.",
                "content": "Doloremque consequuntur odio. Quaerat iusto dolorem veritatis nobis suscipit blanditiis id delectus id. Velit quae sint. Rerum saepe error blanditiis. Neque quia accusamus odit libero earum exercitationem eveniet. Ea vel aut praesentium. Modi harum repudiandae explicabo nam. Labore minima nulla odio molestiae ea consequatur. Non consequatur ut. Inventore eligendi dolore deserunt omnis est ipsum ipsa. Quia laborum placeat qui ut. Sint ab itaque reprehenderit. Consequatur voluptatem quis sequi excepturi non reiciendis ut. Voluptas culpa aut quos ut distinctio perspiciatis cum. In officiis nostrum qui pariatur sit sint et. Rerum soluta rerum neque et. Illo enim in ad asperiores et harum minima iste. Praesentium omnis optio. Dolorem fugit quod unde. Molestias laboriosam sapiente numquam debitis distinctio ipsa dolores qui. Cupiditate omnis consequatur soluta hic aut ipsa eius. Eum harum eius accusamus quis ex. Animi sint quis.",
                "author": {
                    "username": "godsavethequeen",
                    "role": "prime-admin",
                    "id": "60a967d88a5d2d522c0d3111"
                },
                "id": "60ac8cfe8c932132c4fe4163"
            },
            {
                "likes": [],
                "comments": [],
                "createdAt": "2021-05-25T05:36:59.212Z",
                "title": "Eius quod laborum est ipsum.",
                "content": "Corporis deleniti corrupti rerum. Fuga et hic quia placeat eius sit veniam. Vero aut optio facilis laborum suscipit cupiditate. Et sint pariatur sit velit amet voluptatem optio. Consequatur ipsam dolor sequi nobis. Quia modi ut omnis officiis cum est. Blanditiis numquam expedita facere minus in corporis ea eligendi. Voluptas odit adipisci quidem veritatis recusandae nihil placeat. Dolorem velit recusandae. Quis eaque excepturi dolores minima ab. Voluptatem tenetur doloremque. Ratione voluptatem voluptatem non expedita qui odit ut fugit. A tempore esse. Sunt inventore qui. Nihil molestias dolor earum deserunt atque. Facilis qui quia velit et nihil perferendis eveniet sed est. Ipsam saepe animi. Deserunt excepturi et reprehenderit odit aut doloribus nesciunt ratione. Tenetur numquam numquam quaerat ea. Necessitatibus vel iure officia nostrum voluptate perferendis hic molestiae. Quo ea nihil. Quia dolores fugiat cumque labore fugit consequatur. Facere enim est qui aut nihil incidunt omnis harum.",
                "author": {
                    "username": "godsavethequeen",
                    "role": "prime-admin",
                    "id": "60a967d88a5d2d522c0d3111"
                },
                "id": "60ac8cfe8c932132c4fe4139"
            }
        ],
        "total": 77,
        "pages": 39,
        "page": 3,
        "limit": 2,
        "orderBy": "createdAt",
        "orderDir": "desc"
    }
 * @apiSuccess {Object[]} items List of articles.
 * @apiSuccess {String[]} item[likes] Article likes
 * @apiSuccess {String[]} item[comments] Article comments
 * @apiSuccess {String} item[content] Article content
 * @apiSuccess {Object} item[author] Article author
 * @apiSuccess {String} author[username] Article author username
 * @apiSuccess {String} author[role] Article author role
 * @apiSuccess {String} author[id] Article author id
 * @apiSuccess {String} item[id] Article id
 * @apiSuccess {String} item[createdAt] Article created at time - auto-generated by Mongo
 * @apiSuccess {String} item[updatedAt] Article updated at time - auto-generated by Mongo
 * @apiSuccess {Number} total Total number of articles
 * @apiSuccess {Number} pages Total number of pages
 * @apiSuccess {Number} page  Current page
 * @apiSuccess {Number} limit Articles per page
 * @apiSuccess {String} orderBy Order articles by field
 * @apiSuccess {String} orderDir Order articles in desc or asc order
 * @apiError (Error 400) InvalidObjectID <code>Please provide a valid object id.</code>
 * @apiError (Error 400) AuthorizationRequired  <code>The authorization header is required.</code>
 * @apiError (Error 401) NotAuthorized  <code>You are not authorized.</code>
 * @apiError (Error 401) RefreshTokenExpired <code>Refresh token has expired.</code>
 * @apiError (Error 401) AccessTokenExpired <code>Access token has expired.</code>
 * @apiError (Error 404) AccountNotFound <code>Account not found.</code>
 * @apiError (Error 404) ResourceNotFound <code>Resource not found.</code>
 * @apiErrorExample {json} Example Error Response:
    {
        "errors": [
            {
                "message": "Resource not found.",
                "errorType": "ResourceNotFound",
                "statusCode": 404
            }
        ]
    }
 */
